### ISSUE TITLE
BUG: mice and elephant not working 

### ISSUE THREAD

**Issue by eranra** [netobserv/flowlogs-pipeline#103]
Initial investigation shows that we do not create the metrics

**Comment by mariomac** [comment]
Could it be that the Collector Ingest is not really forwarding the metrics as long as they come regularly?

The way I interpret this line: https://github.com/netobserv/flowlogs-pipeline/blob/main/pkg/pipeline/ingest/ingest_collector.go#L153 is that the "flush timer" is restarted each time a new metric arrive, so it won't forward them unless there is 1 complete second without receiving metrics.

**Comment by ronensc** [comment]
The bug seems to be in these lines:
https://github.com/netobserv/flowlogs-pipeline/blob/e0d95f28d1f2973e52b260a73b1e750e5caec990/pkg/pipeline/transform/transform_network.go#L77-L80

The first `%s` corresponds to `outputEntries[rule.Input]` which is float64 (not a string). The error is 
```
`Invalid token: '%!'`
```
But it's swallowed. @eran Is there a reason for not logging the error?

A simple solution would be to change it to `%v`. I'll submit a PR for that...
